apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::149903054702:role/jenkins-ec2-role
      username: jenkins
      groups:
        - system:masters
    - rolearn: arn:aws:iam::149903054702:role/devops-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

