apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: ap-south-1
    roleArn: arn:aws:iam::149903054702:role/eks-secrets-role
    objects: |
      - objectName: db_username
        objectType: secretsmanager
        objectAlias: db_username
      - objectName: db_password
        objectType: secretsmanager
        objectAlias: db_password
      - objectName: api_key
        objectType: secretsmanager
        objectAlias: api_key

  secretObjects:
  - secretName: aws-secrets
    type: Opaque
    data:
      - objectName: db_username
        key: DB_USERNAME
      - objectName: db_password
        key: DB_PASSWORD
      - objectName: api_key
        key: API_KEY
