apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:ap-south-1:149903054702:secret:db_username-*
        objectType: secretsmanager
        objectAlias: db_username
      - objectName: arn:aws:secretsmanager:ap-south-1:149903054702:secret:db_password-*
        objectType: secretsmanager
        objectAlias: db_password
      - objectName: arn:aws:secretsmanager:ap-south-1:149903054702:secret:api_key-*
        objectType: secretsmanager
        objectAlias: api_key

  secretObjects:
  - secretName: aws-secrets
    type: Opaque
    data:
      - objectName: db_username
        key: DB_USERNAME
      - objectName: db_password
        key: DB_PASSWORD
      - objectName: api_key
        key: API_KEY
