apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: ap-south-1
    roleArn: arn:aws:iam::149903054702:role/eks-secrets-role
    objects: |
      - objectName: arn:aws:secretsmanager:ap-south-1:149903054702:secret:db_username-bCNJfT
        objectType: secretsmanager
        jmesPath:
          - path: DB_USERNAME
            objectAlias: DB_USERNAME
      - objectName: arn:aws:secretsmanager:ap-south-1:149903054702:secret:db_password-HGgSQW
        objectType: secretsmanager
        jmesPath:
          - path: DB_PASSWORD
            objectAlias: DB_PASSWORD
      - objectName: arn:aws:secretsmanager:ap-south-1:149903054702:secret:api_key-f3FIV7
        objectType: secretsmanager
        jmesPath:
          - path: API_KEY
            objectAlias: API_KEY

  secretObjects:
  - secretName: aws-secrets
    type: Opaque
    data:
      - objectName: DB_USERNAME
        key: DB_USERNAME
      - objectName: DB_PASSWORD
        key: DB_PASSWORD
      - objectName: API_KEY
        key: API_KEY

